-- Async Saved Asset image derivatives stored in USER_IMAGES and generated by
-- a Cloudflare Queue consumer. Originals remain the source of truth.

ALTER TABLE ai_images ADD COLUMN thumb_key TEXT;
ALTER TABLE ai_images ADD COLUMN medium_key TEXT;
ALTER TABLE ai_images ADD COLUMN thumb_mime_type TEXT;
ALTER TABLE ai_images ADD COLUMN medium_mime_type TEXT;
ALTER TABLE ai_images ADD COLUMN thumb_width INTEGER;
ALTER TABLE ai_images ADD COLUMN thumb_height INTEGER;
ALTER TABLE ai_images ADD COLUMN medium_width INTEGER;
ALTER TABLE ai_images ADD COLUMN medium_height INTEGER;
ALTER TABLE ai_images ADD COLUMN derivatives_status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE ai_images ADD COLUMN derivatives_error TEXT;
ALTER TABLE ai_images ADD COLUMN derivatives_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE ai_images ADD COLUMN derivatives_started_at TEXT;
ALTER TABLE ai_images ADD COLUMN derivatives_ready_at TEXT;
ALTER TABLE ai_images ADD COLUMN derivatives_attempted_at TEXT;
ALTER TABLE ai_images ADD COLUMN derivatives_processing_token TEXT;
ALTER TABLE ai_images ADD COLUMN derivatives_lease_expires_at TEXT;

CREATE INDEX idx_ai_images_derivatives_status_created
  ON ai_images(derivatives_status, created_at DESC);

CREATE INDEX idx_ai_images_derivatives_version_created
  ON ai_images(derivatives_version, created_at DESC);
