-- Owner-approved 2026-10-03 retail configuration. This is BITBI's measured
-- stored-output-duration policy, not a verified Cloudflare billing contract.
-- Preserve every existing rule (including an earlier explicit Seedance override).
-- Existing accepted attempts keep their pinned revision and rates.
INSERT INTO model_pricing_changes
(revision,actor_user_id,change_id,model_id,configuration_key,action,before_json,after_json,created_at)
SELECT revision+1,'owner-authorized-release','seedance-25-custom-output-duration-2026-10-03','bytedance/seedance-2.5',NULL,'save',
 rules_json,json_patch('{"bytedance/seedance-2.5:{\"inputTier\":\"non_video\",\"operation\":\"generate\",\"resolution\":\"480p\"}":{"modelId":"bytedance/seedance-2.5","configuration":{"resolution":"480p","inputTier":"non_video","operation":"generate"},"rates":{"second":70.67943648},"source":"owner_custom_output_duration_2026_10_03"},"bytedance/seedance-2.5:{\"inputTier\":\"video\",\"operation\":\"generate\",\"resolution\":\"480p\"}":{"modelId":"bytedance/seedance-2.5","configuration":{"resolution":"480p","inputTier":"video","operation":"generate"},"rates":{"second":295.91857453},"source":"owner_custom_output_duration_2026_10_03"},"bytedance/seedance-2.5:{\"inputTier\":\"unmapped\",\"operation\":\"generate\",\"resolution\":\"480p\"}":{"modelId":"bytedance/seedance-2.5","configuration":{"resolution":"480p","inputTier":"unmapped","operation":"generate"},"rates":{"second":297.70618673},"source":"owner_custom_output_duration_2026_10_03"},"bytedance/seedance-2.5:{\"inputTier\":\"non_video\",\"operation\":\"generate\",\"resolution\":\"720p\"}":{"modelId":"bytedance/seedance-2.5","configuration":{"resolution":"720p","inputTier":"non_video","operation":"generate"},"rates":{"second":158.95997777},"source":"owner_custom_output_duration_2026_10_03"},"bytedance/seedance-2.5:{\"inputTier\":\"video\",\"operation\":\"generate\",\"resolution\":\"720p\"}":{"modelId":"bytedance/seedance-2.5","configuration":{"resolution":"720p","inputTier":"video","operation":"generate"},"rates":{"second":665.26675816},"source":"owner_custom_output_duration_2026_10_03"},"bytedance/seedance-2.5:{\"inputTier\":\"unmapped\",\"operation\":\"generate\",\"resolution\":\"720p\"}":{"modelId":"bytedance/seedance-2.5","configuration":{"resolution":"720p","inputTier":"unmapped","operation":"generate"},"rates":{"second":297.70618673},"source":"owner_custom_output_duration_2026_10_03"}}',rules_json),strftime('%Y-%m-%dT%H:%M:%fZ','now')
FROM model_pricing_state WHERE id=1;
UPDATE model_pricing_state SET revision=revision+1,
 rules_json=(SELECT after_json FROM model_pricing_changes WHERE change_id='seedance-25-custom-output-duration-2026-10-03'),
 change_id='seedance-25-custom-output-duration-2026-10-03',updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=1;
